[mastodon]
instance_url = https://mastodon.social
access_token = YOUR_ACCESS_TOKEN_HERE

[images]
directory = /srv/images
; Sorting order: name, size, time
sort_order = name
; Optional status text (if empty, the filename is used)
status_text =
